version: '3.8'

services:

  postgres:
    image: postgres:15-alpine
    container_name: challenge-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: challenge
      POSTGRES_USER: challenge
      POSTGRES_PASSWORD: challenge
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U challenge -d challenge" ]
      interval: 10s
      timeout: 5s
      retries: 10

  kafka:
    image: redpandadata/redpanda:latest
    container_name: challenge-kafka
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - 512M
      - --reserve-memory
      - 0M
      - --node-id
      - "0"
      - --check=false
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"
    healthcheck:
      test: [ "CMD-SHELL", "rpk cluster health | grep -E 'Healthy|true' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 20
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: challenge-kafka-ui
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      kafka:
        condition: service_healthy

  api:
    image: challenge-api:${APP_VERSION:-local}
    build:
      context: .
    container_name: challenge-api
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: local

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/challenge
      SPRING_DATASOURCE_USERNAME: challenge
      SPRING_DATASOURCE_PASSWORD: challenge

      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

volumes:
  postgres_data:
