spring.application.name=challenge-local

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/challenge
spring.datasource.username=challenge
spring.datasource.password=challenge
spring.datasource.driver-class-name=org.postgresql.Driver

# Database
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# Flyway and Migration
spring.flyway.enabled=true
spring.flyway.baseline-description=baseline -local- schema before Flyway

# Kafka Servers
spring.kafka.bootstrap-servers=localhost:9092

# Kafka Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=10
spring.kafka.producer.properties.linger.ms=10
spring.kafka.producer.properties.batch.size=32768
spring.kafka.producer.properties.compression.type=lz4
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.request.timeout.ms=30000
spring.kafka.producer.properties.delivery.timeout.ms=120000
spring.kafka.producer.properties.spring.json.add.type.headers=false
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5

# Kafka Consumer
spring.kafka.listener.ack-mode=manual
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false

# Batch
spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always

# Kafka Topics and Consumers configuration custom properties
challenge.kafka.topics.preference-events=communication-preference-events
challenge.kafka.consumers.preference-event-logger.enabled=true
challenge.kafka.consumers.preference-event-logger.group-id=challenge-preference-event-logger
