spring.application.name=challenge

server.port=8080

# Actuator
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info,metrics,prometheus

spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
