spring.application.name=challenge

server.port=8080

# Actuator
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info,metrics,prometheus

# Serialization
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=UTC

# Database
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Flyway and Migration
spring.flyway.enabled=false
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-description=baseline ENV schema before Flyway

# Kafka Producer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=10
spring.kafka.producer.properties.linger.ms=10
spring.kafka.producer.properties.batch.size=32768
spring.kafka.producer.properties.compression.type=lz4
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.request.timeout.ms=30000
spring.kafka.producer.properties.delivery.timeout.ms=120000
spring.kafka.producer.properties.spring.json.add.type.headers=false
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Kafka Consumer
spring.kafka.listener.ack-mode=manual
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Batch
spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always

# Kafka Topics and Consumers configuration custom properties
challenge.kafka.topics.preference-events=communication-preference-events
challenge.kafka.consumers.preference-event-logger.enabled=false
challenge.kafka.consumers.preference-event-logger.group-id=challenge-preference-event-logger
